### ISSUE TITLE
Unable to debug on Visual Studio 2017.

### ISSUE THREAD

**Issue by ghost** [aspose-cad/Aspose.CAD-for-.NET#2]
I have followed the [Documentation](https://docs.aspose.com/display/cadnet/How+to+Run+the+Examples) and upgraded the Aspose.CAD to the latest version(v17.9.0) by NuGet Packages Manager. But when I open the sample project on VS2017, it's unable to through debugging and I received many error messages.
![1509610442](https://user-images.githubusercontent.com/13387978/32315851-dfe1bf6a-bfe8-11e7-9f2c-8ab42a9895a5.jpg)
What should I do? 
@Muhammad-Adnan-Ahmad @aspose-cad 
Thanks.

**Comment by Muhammad-Adnan-Ahmad** [comment]
@weipf8 ,

We are working over fixing the examples on our end and will push the changes as soon as possible. I request for your patience till the time we push updates.

**Comment by aspose-cad** [comment]
@weipf8 ,

We have updated the git examples in accordance with Aspose.CAD for .NET 17.9. Can you please try using the latest examples on your end.

**Comment by ghost** [comment]
Duplicate of # @aspose-cad 
Thanks! The latest examples can be run successfully.
