### ISSUE TITLE
Text Search For DXF and DGN

### ISSUE THREAD

**Issue by gmalenko** [aspose-cad/Aspose.CAD-for-.NET#4]
Hello,

Is it possible to do a text search on the dxf and dgn formats?  You have an example for the dwg format.  If so, is there an example?  It would seem that the example for dwg doesn't work in this case.

**Comment by aspose-cad** [comment]
@gmalenko ,

We are checking requirements on our end and will share the feedback with you as ASAP.

**Comment by aspose-slides** [comment]
@gmalenko ,

Can you please try using the sample code over following Git link on your end for DXF file as well and share if it works for your not. I have tried the same sample code on my end for a DXF and code executed without any issue.
https://github.com/aspose-cad/Aspose.CAD-for-.NET/blob/master/Examples/CSharp/DWG-Drawings/SearchText.cs

**Comment by aspose-cad** [comment]
@gmalenko ,
Can you please try using the sample code over following Git link on your end for DXF file as well and share if it works for your not. I have tried the same sample code on my end for a DXF and code executed without any issue.
https://github.com/aspose-cad/Aspose.CAD-for-.NET/blob/master/Examples/CSharp/DWG-Drawings/SearchText.cs
